/**
 * Firestore Types & Interfaces
 * Defines the structure of data stored in Firebase Firestore
 */

import { Timestamp } from "firebase/firestore";

/**
 * Browser Scan Result
 * Stored in the 'browser_scans' collection
 */
export interface BrowserScan {
  // Document ID (auto-generated by Firestore)
  id?: string;

  // URL Information
  url: string;
  hostname: string;
  browserTitle: string;
  favicon?: string;

  // Security Analysis
  trustScore: number; // 0-100
  threatLevel: "HIGH" | "MEDIUM" | "LOW" | "SAFE";
  phishingRisk: number; // 0-100 (probability)
  manipulationScore: number; // 0-100

  // Detailed Analysis
  riskFactors: string[];
  aiExplanation: string;

  // Metadata
  scannedAt: Timestamp | Date;
  userId?: string;

  // Statistics
  httpStatus?: number;
  loadTime?: number;
  certificateValid?: boolean;
}

/**
 * Aggregated Statistics
 * Used for dashboard displays
 */
export interface DashboardStats {
  totalScans: number;
  threatsDetected: number;
  averageTrustScore: number;
  highThreats: number;
  mediumThreats: number;
  lowThreats: number;
  safeSites: number;
  lastUpdated: Date;
}

/**
 * Recent Threat Alert
 * Used in live threat feed
 */
export interface ThreatAlert {
  id: string;
  url: string;
  threatLevel: string;
  trustScore: number;
  timestamp: Date;
  reason: string;
}

/**
 * Threat Category
 */
export type ThreatCategory =
  | "Phishing"
  | "Malware"
  | "Scam"
  | "Typosquat"
  | "Credentials"
  | "Redirect"
  | "Suspicious"
  | "Safe";

/**
 * URL Analysis Request
 */
export interface URLAnalysisRequest {
  url: string;
}

/**
 * URL Analysis Response
 */
export interface URLAnalysisResponse {
  trustScore: number;
  threatLevel: string;
  phishingRisk: number;
  manipulationScore: number;
  riskFactors: string[];
  aiExplanation: string;
  category: ThreatCategory;
}
