/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZeroTrustRouteImport } from './routes/zero-trust'
import { Route as UrlProtectionRouteImport } from './routes/url-protection'
import { Route as TrustEngineRouteImport } from './routes/trust-engine'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ScamDetectionRouteImport } from './routes/scam-detection'
import { Route as DeepfakeDefenseRouteImport } from './routes/deepfake-defense'
import { Route as BrowserShieldRouteImport } from './routes/browser-shield'
import { Route as IndexRouteImport } from './routes/index'

const ZeroTrustRoute = ZeroTrustRouteImport.update({
  id: '/zero-trust',
  path: '/zero-trust',
  getParentRoute: () => rootRouteImport,
} as any)
const UrlProtectionRoute = UrlProtectionRouteImport.update({
  id: '/url-protection',
  path: '/url-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustEngineRoute = TrustEngineRouteImport.update({
  id: '/trust-engine',
  path: '/trust-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamDetectionRoute = ScamDetectionRouteImport.update({
  id: '/scam-detection',
  path: '/scam-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepfakeDefenseRoute = DeepfakeDefenseRouteImport.update({
  id: '/deepfake-defense',
  path: '/deepfake-defense',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserShieldRoute = BrowserShieldRouteImport.update({
  id: '/browser-shield',
  path: '/browser-shield',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browser-shield': typeof BrowserShieldRoute
  '/deepfake-defense': typeof DeepfakeDefenseRoute
  '/scam-detection': typeof ScamDetectionRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/trust-engine': typeof TrustEngineRoute
  '/url-protection': typeof UrlProtectionRoute
  '/zero-trust': typeof ZeroTrustRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browser-shield': typeof BrowserShieldRoute
  '/deepfake-defense': typeof DeepfakeDefenseRoute
  '/scam-detection': typeof ScamDetectionRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/trust-engine': typeof TrustEngineRoute
  '/url-protection': typeof UrlProtectionRoute
  '/zero-trust': typeof ZeroTrustRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browser-shield': typeof BrowserShieldRoute
  '/deepfake-defense': typeof DeepfakeDefenseRoute
  '/scam-detection': typeof ScamDetectionRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/trust-engine': typeof TrustEngineRoute
  '/url-protection': typeof UrlProtectionRoute
  '/zero-trust': typeof ZeroTrustRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browser-shield'
    | '/deepfake-defense'
    | '/scam-detection'
    | '/sign-in'
    | '/sign-up'
    | '/trust-engine'
    | '/url-protection'
    | '/zero-trust'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browser-shield'
    | '/deepfake-defense'
    | '/scam-detection'
    | '/sign-in'
    | '/sign-up'
    | '/trust-engine'
    | '/url-protection'
    | '/zero-trust'
  id:
    | '__root__'
    | '/'
    | '/browser-shield'
    | '/deepfake-defense'
    | '/scam-detection'
    | '/sign-in'
    | '/sign-up'
    | '/trust-engine'
    | '/url-protection'
    | '/zero-trust'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowserShieldRoute: typeof BrowserShieldRoute
  DeepfakeDefenseRoute: typeof DeepfakeDefenseRoute
  ScamDetectionRoute: typeof ScamDetectionRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TrustEngineRoute: typeof TrustEngineRoute
  UrlProtectionRoute: typeof UrlProtectionRoute
  ZeroTrustRoute: typeof ZeroTrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zero-trust': {
      id: '/zero-trust'
      path: '/zero-trust'
      fullPath: '/zero-trust'
      preLoaderRoute: typeof ZeroTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/url-protection': {
      id: '/url-protection'
      path: '/url-protection'
      fullPath: '/url-protection'
      preLoaderRoute: typeof UrlProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-engine': {
      id: '/trust-engine'
      path: '/trust-engine'
      fullPath: '/trust-engine'
      preLoaderRoute: typeof TrustEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scam-detection': {
      id: '/scam-detection'
      path: '/scam-detection'
      fullPath: '/scam-detection'
      preLoaderRoute: typeof ScamDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deepfake-defense': {
      id: '/deepfake-defense'
      path: '/deepfake-defense'
      fullPath: '/deepfake-defense'
      preLoaderRoute: typeof DeepfakeDefenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser-shield': {
      id: '/browser-shield'
      path: '/browser-shield'
      fullPath: '/browser-shield'
      preLoaderRoute: typeof BrowserShieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowserShieldRoute: BrowserShieldRoute,
  DeepfakeDefenseRoute: DeepfakeDefenseRoute,
  ScamDetectionRoute: ScamDetectionRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TrustEngineRoute: TrustEngineRoute,
  UrlProtectionRoute: UrlProtectionRoute,
  ZeroTrustRoute: ZeroTrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
